#my variables
name: Aadesh Shrestha
description: just personal blog
google_analytics: UA-77211589-1
teletext: 47e654e9-b8f3-4c1e-ba85-23c7c013deef
# baseurl: "/example"

include: [".htaccess"]
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

#css settings
sass:
  style: :compressed
  sass_dir: _sass
#Build settings
markdown: kramdown
